# Generated by Django 5.1.1 on 2024-09-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sent_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
