# Generated by Django 5.1.1 on 2024-09-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='Help!', max_length=200),
        ),
    ]
