# Generated by Django 5.1.1 on 2024-09-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250, unique=True)),
                ('review', models.TextField()),
                ('user_image', models.ImageField(default='UserImage.jpg', upload_to='reviews/')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
