# Generated by Django 5.1.1 on 2024-09-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_reviews_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
