# Generated by Django 5.1.1 on 2024-09-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_reviews_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
