# Generated by Django 5.1.1 on 2024-09-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_contact_responded_email_responded'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_no',
            field=models.CharField(default='+123 456 7890', max_length=20),
        ),
    ]
