# Generated by Django 5.1.1 on 2024-09-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_contact_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(default='+123 456 7890', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('office_location', models.CharField(max_length=100)),
            ],
        ),
    ]
