# Generated by Django 5.1.1 on 2024-12-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_remove_contact_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user_image',
        ),
    ]
