# Generated by Django 5.1.1 on 2024-12-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_remove_reviews_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
