# Generated by Django 5.1.1 on 2024-09-19 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralContracting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(default='gen_service.png', upload_to='general-services/')),
            ],
        ),
        migrations.CreateModel(
            name='BulletPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('gen_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_points', to='services.generalcontracting')),
            ],
        ),
    ]
