# Generated by Django 5.1.1 on 2024-09-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_generalcontracting_bulletpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcontracting',
            name='home_pg_display',
            field=models.BooleanField(default=False),
        ),
    ]
