# Generated by Django 5.1.1 on 2024-09-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_generalcontracting_home_pg_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalcontracting',
            name='slug',
        ),
    ]
