# Generated by Django 5.1.1 on 2024-10-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_generalcontracting_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulletPoints',
        ),
        migrations.DeleteModel(
            name='GeneralContracting',
        ),
    ]
