# Generated by Django 5.1.1 on 2024-09-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='latest',
            field=models.BooleanField(default=False),
        ),
    ]
