# Generated by Django 5.1.1 on 2024-09-12 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogimage_blogreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogreply',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
