# Generated by Django 5.1.1 on 2024-09-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_quotes_alter_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='featured_image',
            new_name='image',
        ),
    ]
