"""
Django settings for renovation project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m%yb6bt7-ywnzoam04aam(m0oyy2fav_8s6e)xneh18$$vztq%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['naafycontracting.com', 'www.naafycontracting.com', 'naafycontracting.ca', 'www.naafycontracting.ca', 'mail.naafycontracting.com']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'aboutus',
    'blog',
    'contact',
    'services',
    'useradmin'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'renovation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'home.context_processors.default',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'renovation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Toronto'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'useradmin:login'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.naafycontracting.com' 
EMAIL_PORT = 465  # Port for TLS
EMAIL_USE_TLS = False  # Use TLS (Transport Layer Security)
EMAIL_USE_SSL = True  # Do not use SSL
EMAIL_HOST_USER = 'info@naafycontracting.com'  # Your Microsoft email
EMAIL_HOST_PASSWORD = '@Naafy@1234@'  # Your Microsoft email password
DEFAULT_FROM_EMAIL = 'info@naafycontracting.com'  # Default "From" email address
EMAIL_TIMEOUT = 30  # 10 seconds timeout


JAZZMIN_SETTINGS = {
    # Title of the window (defaults to the current_admin_site.site_title)
    "site_title": "Naafy Contracting",

    # Title on the login screen (defaults to current_admin_site.site_header)
    "site_header": "Naafy Contracting",

    # Title on the brand (defaults to current_admin_site.site_header)
    "site_brand": "Naafy Contracting!",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "assets1/imgs/theme/b-logo.ico",

    # Small text logo for the top left (19 chars max)
    "site_logo_text": "Naafy Contracting",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to Your Admin Portal",

    # Copyright text in the footer
    "copyright": "Naafy Contracting © 2024",

    # The model name or import path to the user model, used by Jazzmin to power the user menu
    "user_model": "auth.User",

    # Links to put along the top bar
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://support.site.com", "new_window": True},
    ],

    # Custom links to be included in the user menu dropdown
    "usermenu_links": [
        {"name": "Profile", "url": "profile", "icon": "fas fa-user"},
    ],

    # Custom icons for models and apps
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },

    # Change the color scheme, theme, and other styling
    "theme": "lux", # Enables a live UI builder for customization
}