# Generated by Django 5.1.1 on 2024-09-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0002_profile_address_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.EmailField(max_length=254)),
                ('email_host_password', models.CharField(max_length=255)),
                ('default_from_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('is_active', True)), name='only_one_active_email_settings')],
            },
        ),
    ]
