# Generated by Django 5.1.1 on 2024-09-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0004_emailconfiguration_delete_emailsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfiguration',
        ),
    ]
